name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 📥 Download
        run: npm run lerna:bootstrap:ci

      - name: ▶️ Run tests
        run: |
          npm run clean
          npm run lint
          npm run copy:static
          npm run build:prod
          INSTALL_CMD="echo 'happo-ci-travis'" npm run happo-ci-travis
        env:
          HAPPO_API_KEY: ""
          HAPPO_API_SECRET: ""
